language: java
env:
  matrix:
  - IDEA_VERSION=LATEST-EAP-SNAPSHOT
  global:
    secure: DYayIqO89y8cJiIe0DJ4I1yeFrBZiKYtLphmr9SJCU7KUxEuXto0xcb2z4xnjkw84P8LAOgcrpav+1tpP4MTyZ7OT/bGR6ONxD0y2jkiamQq7EPPFr5nFI5unX8VXKjahrdS5xPjsULa1IprJ/QAslDdTKxoxLtM4j4vEedZ2Ob4lepGnD2FhzTm5kFZuoS44oxJXgRxa+Xn1FOQTv4PhiGz8Jm0HeokKZDXEqjizEbZf29vENGWIyuJV0nYJsbd9YU/PWS8yaFpAy3+J5bsYL1v3l0+FVcg64Bujxkf3xzPS3tuLCFmYnLUCt2qgk18C3eSyYBpIOKtW3oyj8SNYKKVk6aL6XMqSEnIFDuyiZxMJDafdeQJDCPy1LbVrWL1KNNdFGQivNHvWTgCyjHTtVuYsem6qDMbVVcqm13LQa3V21M/MPs/bmqbGaETZ4fm6yJYT8X8iH+wmhYN0f0X/urp0DfAcBZKv1pFtvQngSb5xgkf7ijq11jM7XWUgTNoHBD+pUHLpL4KrfTgvKqBKzqpLVU6kms2YWaRt842/2QZRGn60U1EUfM2S7Iwk0vGR59UXYS0tM/7PXG7yGU9kXF5VQ9zpPAslEGUKLZuVZvO/KUxBhToZaxFUUTc9543X0/3zHRuBmF8my2O/BKEOidtmTelgCxUfuD4/ZHcJog=
jdk:
- oraclejdk8
script:
- ./gradlew test -PideaVersion=$IDEA_VERSION
notifications:
  email: false
cache:
  directories:
  - $HOME/.m2
  - $HOME/.gradle
after_success:
- .travis/after_success.sh
before_install:
- openssl aes-256-cbc -K $encrypted_9f6ec11ac5b3_key -iv $encrypted_9f6ec11ac5b3_iv
  -in travis.enc -out .travis.ssh -d
- chmod 600 .travis.ssh
- echo -e "Host github.com\n\tStrictHostKeyChecking no\nIdentityFile .travis.ssh\n"
  >> ~/.ssh/config
